# Generated by Django 5.2.4 on 2025-07-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_blogpost_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
    ]
